url_new:
    pattern:  /
    defaults: { _controller: KtIoWebInterfaceBundle:Url:new }

url_fetch:
    pattern: /{hash}
    defaults: { _controller: KtIoWebInterfaceBundle:Url:fetch }

url_show:
    pattern: /show/{id}
    defaults: { _controller: KtIoWebInterfaceBundle:Url:show }
